### ISSUE TITLE
Incorrect labels in Figure 5 of API Definition v1.0

### ISSUE THREAD

**Issue by matdehaast** [mojaloop/documentation#4]
Figure 5 in the API Definition is used to describe the flow of swapping the source and destination headers when the destination is unknown by the sending DFSP. It incorrectly labels _FSPIOP-Destination_ as _FSPIOP- Source_ in the whole flow

**Comment by elnyry** [comment]
Thanks Matt for this.

One of the CCB members identified this as well (on Feb21st) and this will be fixed with an update soon. A change proposal is on the way..

Also, for the spec related issues, an you raise it on the mojaloop-specification repo?
